
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button HiButton;

	private global::Gtk.Entry userNameInput;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.HiButton = new global::Gtk.Button();
		this.HiButton.CanFocus = true;
		this.HiButton.Name = "HiButton";
		this.HiButton.UseUnderline = true;
		this.HiButton.Xalign = 0.6F;
		this.HiButton.Yalign = 0.58F;
		this.HiButton.Label = global::Mono.Unix.Catalog.GetString("Hello");
		this.fixed1.Add(this.HiButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.HiButton]));
		w1.X = 200;
		w1.Y = 138;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.userNameInput = new global::Gtk.Entry();
		this.userNameInput.CanFocus = true;
		this.userNameInput.Name = "userNameInput";
		this.userNameInput.IsEditable = true;
		this.userNameInput.InvisibleChar = '●';
		this.fixed1.Add(this.userNameInput);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.userNameInput]));
		w2.X = 97;
		w2.Y = 56;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.HiButton.Pressed += new global::System.EventHandler(this.OnHiButtonPressed);
	}
}
